### ISSUE TITLE
registry_namespace: consider deleting state as deleted

### ISSUE THREAD

**Issue by Codelax** [scaleway/terraform-provider-scaleway#1735]
There is currently issues making namespace long to delete.
As a workaround we can consider it as deleted when the status is deleting

**Comment by gbegher** [comment]
I would consider it as deleted when status is "deleting" independently of the deletion time.

The reasoning:

* I expect TF to manage my resources.
* If TF says some resource is fine, I expect to be able to use it.


Scenario:
* Some part of my pipeline creates the namespace.
* Some later step in the pipeline tries to push an image.

Expected behaviour would be:

* TF creates a new namespace
* My pipeline uses the new registry down the line

Actual behaviour:

* TF says everything is fine
* Pipeline fails down the line (docker push gets rejected since the namespace is marked for deletion)
