### ISSUE TITLE
Configuration does not work with environment variable

### ISSUE THREAD

**Issue by marcw** [scaleway/terraform-provider-scaleway#286]
I keep getting the following error:

`Error: error loading credentials from SCW: open /my/home/dir/.scwrc: no such file or directory`

even if I set the `SCW_SECRET_KEY` or `SCALEWAY_SECRET_KEY` environment variable.

**Comment by kindermoumoute** [comment]
Can you give us your terraform version and your Scaleway provider? (run `terraform version` in your working directory)

**Comment by marcw** [comment]
Sure. Here it is:

```
Terraform v0.12.11
[...]
+ provider.scaleway v1.11.0
```

**Comment by kindermoumoute** [comment]
I could not reproduce the above issue:

```bash
$ export SCW_SECRET_KEY=XXXX 
$ terraform plan
... (works)
```

Make sure `SCW_SECRET_KEY` is not an empty variable.

This said, the error is not self-explanatory and should not encourage to use `/my/home/dir/.scwrc`.

**Comment by marco-m** [comment]
I can confirm that the 3 environment variables `SCW_DEFAULT_ORGANIZATION_ID`,` SCW_ACCESS_KEY`
and `SCW_SECRET_KEY` are read correctly by the scaleway provider.

```
terraform --version
Terraform v0.12.18
+ provider.scaleway v1.13.0
```

I also agree with @kindermoumoute:

> the error is not self-explanatory and should not encourage to use /my/home/dir/.scwrc

since it is not secure. Clearly the environment variables by themselves are not secure either, but can be made secure with tools such as [envchain](https://github.com/sorah/envchain) or [pass](https://www.passwordstore.org/) or [gopass](https://github.com/gopasspw/gopass).

**Comment by remyleone** [comment]
We remove dependencies on the previous configuration file `.scwrc` in favor of the new one `~/.config/scw/config.yaml`. Don't hesitate to open a new issue in case you stumble upon another problem.
