### ISSUE TITLE
Add support for private networks

### ISSUE THREAD

**Issue by jerome-quere** [scaleway/terraform-provider-scaleway#489]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add resource to manage instance private networks

**Comment by debackerl** [comment]
When creating a Kubernetes kapsule pool, it would be good to have the ability to specify private networks to be attached nodes created for the pool. However, since nodes in a pool is dynamic and the OS is managed by you, you would need to configure the nodes to use DHCP to get an IP.

Thanks, and keep up the good work!!!
