### ISSUE TITLE
Can't spawn dev1-l/xl with additional volumes

### ISSUE THREAD

**Issue by evgeniwk** [scaleway/terraform-provider-scaleway#519]
### Terraform Version
Terraform v0.12.9
+ provider.scaleway v1.16.0

### Affected Resource(s)

* scaleway_instance_server
* scaleway_instance_volume

### Terraform Configuration Files

```hcl
resource "scaleway_instance_volume" "data" {
  size_in_gb = 100
  type = "b_ssd"
}
resource "scaleway_instance_server" "web" {
  type = "DEV1-L"
  image = "ubuntu-bionic"
  tags = [ "hello", "public" ]
  root_volume {
    delete_on_termination = false
  }
  additional_volume_ids = [ scaleway_instance_volume.data.id ]
}
```

### Debug Output
https://gist.github.com/evgeniwk/c94e251357eb1eee152551cd9a698784

### Expected Behavior

Create an instance with additional volumes

### Actual Behavior

`Error: scaleway-sdk-go: http error 400 Bad Request: the total size of local-volume(s) of instances dev1-l must be equal to 80gb`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

```
  root_volume {
    size_in_gb = 80
    delete_on_termination = false
  }
```
solves the issue

**Comment by Sh4d1** [comment]
So yep, in the API, asking a server without a volume (so that without the size in root volume and without any additional volumes, will create a volume of the right size. 

When additionals volumes are provided, without the size in the root volume, only the additional volumes are sent in the volume request, leading the API to create a volume from the image, without resizing it, leading to a 50G volume. 

This can be solved on both side though. 

On TF side, we could always send the root volume size if not provided (this would be good to do anyway) (and I think we have the mapping instance type -> volume size. We would just need to calculate the size based on l_ssd additional volumes.

On the API it's a bit trickier though 🤔

**Comment by BasilHaas** [comment]
Same issue. Is it possible to add this solution to the [documentation](https://www.terraform.io/docs/providers/scaleway/r/instance_server.html#with-additional-volumes-and-tags) page?

**Comment by cchaudier** [comment]
Hello, 
I've this pb with GP1-XS.
But it work with DEV1-S...
```
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/terraform-providers/ovh v0.9.1
+ provider registry.terraform.io/terraform-providers/scaleway v1.16.0
```

Il put one aditionnal volume on my instances.

I fixed the problem by specifying root_volume.size_in_gb.
But it made me add code that I consider unnecessary.
Is not the KISS way for me.
