### ISSUE TITLE
Refactor beta resources

### ISSUE THREAD

**Issue by remyleone** [scaleway/terraform-provider-scaleway#561]
A lot of our resources got "beta" in their name. It is cumbersome to type it and does not reflect the fact that some API are considered stable. We need a way to convert the beta resources to stable ones.

**Option 1: Use an environment variable to explicitly enable those resources**

We would disable those resources, replace them with new ones by default and only enable a backward compatibility option with them through an environment variable such as `TF_BETA_RESOURCES=1`. By doing so, when a customer upgrade terraform version they will migrate their state/resources to new ones. Or have the option to keep the old version to still work using the environment variable.

**Comment by marco-m** [comment]
As a user, I was confused by the "beta" in resource names, so this is a +1 to remove them.

On the other hand, if I understand what is proposed here, the name `TF_BETA_RESOURCES` would be, once again, confusing.  I would suggest something along the lines of `TF_SCW_ALLOW_DEPRECATED_BETA_RESOURCES`.

`SCW` because namespacing is important.
`DEPRECATED` because it describes what it actually is. Something like `TF_BETA_RESOURCES` would give the idea that one could enable some, well, beta features :-)
