### ISSUE TITLE
scaleway_k8s_cluster: maintenance values are not optional

### ISSUE THREAD

**Issue by gmile** [scaleway/terraform-provider-scaleway#819]
### Terraform Version

0.15.1

### Affected Resource(s)

* scaleway_k8s_cluster

### Terraform Configuration Files

```hcl
resource "scaleway_k8s_cluster" "k8s_cluster" {
  name    = "my-k8s-cluster-staging"
  version = "1.20.4"
  cni     = "cilium"

  auto_upgrade {
    enable = false
  }
}
```

### Debug Output

```
terraform apply
╷
│ Error: Missing required argument
│
│   on ../sources/main.tf line 14, in resource "scaleway_k8s_cluster" "k8s_cluster":
│   14:   auto_upgrade {
│
│ The argument "maintenance_window_day" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│
│   on ../sources/main.tf line 14, in resource "scaleway_k8s_cluster" "k8s_cluster":
│   14:   auto_upgrade {
│
│ The argument "maintenance_window_start_hour" is required, but no definition was found.
$
```

### Panic Output

None.

### Expected Behavior

Values for `maintenance_window_day` and `maintenance_window_start_hour` attributes are not required in case `enable` is set to `false` for `auto_upgrade`.

According to [documentation](https://github.com/scaleway/terraform-provider-scaleway/blob/d72b0b978d35fc3b294d15761254f7c940d9a065/docs/resources/k8s_cluster.md#L144), the values are optional.

### Actual Behavior

Terraform returns an error warning about attributes not being set.

### Steps to Reproduce

1. create a config file from sample above,
2. run `terraform apply`

### Important Factoids

None.

### References

None.

**Comment by Sh4d1** [comment]
Hello 👋 Indeed for now the values are required in the optional `auto_upgrade` block :p 
So either, drop the `auto_upgrade` block -> it's disabled per default
Or you can set the values, which will be ignored since the `auto_upgrade` will be disable.

I'lll try to think of a solution, but Terraform isn't exaclty flexible sometimes 😅

**Comment by gmile** [comment]
> So either, drop the auto_upgrade block -> it's disabled per default

Really? 🤔 The very reason why I stumbled upon the issue was that I didn't have the minor version in my k8s cluster version and got an error saying that `auto_upgrade` needs it, which made me think that auto_upgrade is on by default

**Comment by Sh4d1** [comment]
Ah yeah, if you set the only the minor version, you'll need autoupgrade, otherwise use the full version with the patch :)

**Comment by Sh4d1** [comment]
Are you running the latest provider release? It works for me with the latest

**Comment by u2m4c6** [comment]
After talking with someone very helpful from Scaleway support, the first thing that solved this issue was using hardcode values and no variable files in my terraform resource definition file.

I was then also able to get auto_upgrade to work with variables by changing the name of the pool from "primary pool" to "primary_pool". I am not sure why variables/a space in the pool name is messing up the version check, but that is what it seems like on my end.

Versions: Terraform 1.0.5, Scaleway provider 2.1.0 and Kubernetes 1.22 (1.22.1 once the cluster is created).
